/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Yago;

import javax.swing.JOptionPane;

/**
 *
 * @author yagov
 */
public class Disciplinas extends javax.swing.JFrame {
    String crs = trabalho.getCurso();
    static int qnt = trabalho.getQuantCurso();
    static String materias[] = new String[qnt];
    int i = 0;
    int cfrm = 6;
    

  
    public Disciplinas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Confirm = new javax.swing.JLabel();
        ButDisc = new javax.swing.JButton();
        Disciplina = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Louis George Café Light", 1, 24)); // NOI18N
        jLabel1.setText("Informe as Disciplinas");

        Confirm.setFont(new java.awt.Font("Louis George Café Light", 1, 14)); // NOI18N

        ButDisc.setFont(new java.awt.Font("Louis George Café Light", 1, 14)); // NOI18N
        ButDisc.setText("Enviar");
        ButDisc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButDiscMouseClicked(evt);
            }
        });
        ButDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButDiscActionPerformed(evt);
            }
        });

        Disciplina.setFont(new java.awt.Font("Louis George Café Light", 0, 14)); // NOI18N
        Disciplina.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DisciplinaFocusGained(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Louis George Café Light", 1, 14)); // NOI18N
        jLabel2.setText("Curso: "+crs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(ButDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Confirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Disciplina))
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(Disciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(ButDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButDiscActionPerformed
        // TODO add your handling code here:
        
       if(i==qnt-1){
                cfrm = JOptionPane.showConfirmDialog(null,"Os dados estao corretos?","todas as "+qnt+" materias inseridas",JOptionPane.YES_NO_OPTION);
                if(cfrm == 0){
                    Alunos alunos = new Alunos();
                    alunos.setVisible(true);
                    alunos.pack();
                    alunos.setLocationRelativeTo(null);
                    alunos.setDefaultCloseOperation(trabalho.EXIT_ON_CLOSE);
                    this.setVisible(false);
                    
                }
                else{
                    i=0;
                    Confirm.setText("REINSIRA AS DISCIPLINAS");
                    Disciplina.setText(null);
                    return;
                    
                }
                
            }
            materias[i] = Disciplina.getText();
            Confirm.setText(materias[i] + " inserida, insira a proxima."); 
            System.out.println(materias[i]);
            i++;
            
            
        
        
            
        
    }//GEN-LAST:event_ButDiscActionPerformed

    public static String[] getMaterias() {
        return materias;
    }

    private void ButDiscMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButDiscMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ButDiscMouseClicked

    private void DisciplinaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DisciplinaFocusGained
        SetNull();
    }//GEN-LAST:event_DisciplinaFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Disciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Disciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Disciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Disciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Disciplinas().setVisible(true);
            }
        });
    }
    
    public void SetNull(){
        Disciplina.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButDisc;
    private javax.swing.JLabel Confirm;
    private javax.swing.JTextField Disciplina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
